"""
Handwritten/scanned paper-form extraction tool.

Takes a scanned or photographed PDF of a COMPLETED rigid-checklist price form
(generated by build_paper_form.*.py) and produces the two schema output
tables (submissions, line_items) as CSVs.

How it works: the form's field-map JSON (produced alongside the blank form)
records the exact page position of every checkbox and price box, so this
tool never has to read item names off the page -- it only has to (1) decide
whether a pre-printed item's checkbox is filled in, and (2) OCR the digits
in the price box next to it. Only the small number of write-in rows require
reading open handwritten text, and those are always flagged for review.

Usage:
    python3 extract_paper_form.1.0.py <pdf_path> <fieldmap.json> <schema.json> <output_basename>
    python3 extract_paper_form.1.0.py --batch <folder_of_pdfs> <fieldmap.json> <schema.json> <output_basename>
"""

import sys
import glob
import json
import re
import numpy as np
import pandas as pd
import pytesseract
from PIL import Image
from pdf2image import convert_from_path
from reportlab.lib.pagesizes import A4

DPI = 300
PAGE_H_PTS = A4[1]  # PDF field-map coordinates are in points, origin bottom-left
CHECKBOX_DARK_FRACTION = 0.15  # fraction of dark pixels inside the box to call it "filled"
INSET_PX = 2  # shrink crops inward by this many px to avoid counting the box's own border


def pt_bbox_to_px(bbox_pts, dpi=DPI, page_h_pts=PAGE_H_PTS):
    """Convert a [x0,y0,x1,y1] bbox in PDF points (bottom-left origin) to
    pixel coordinates (top-left origin) at the given render DPI."""
    scale = dpi / 72.0
    x0, y0, x1, y1 = bbox_pts
    px_x0 = x0 * scale
    px_x1 = x1 * scale
    px_y0 = (page_h_pts - y1) * scale
    px_y1 = (page_h_pts - y0) * scale
    return (px_x0, px_y0, px_x1, px_y1)


def crop(img, bbox_px, inset=INSET_PX):
    x0, y0, x1, y1 = bbox_px
    x0, y0, x1, y1 = x0 + inset, y0 + inset, x1 - inset, y1 - inset
    return img.crop((max(0, x0), max(0, y0), x1, y1))


def is_checkbox_filled(img_crop, threshold=CHECKBOX_DARK_FRACTION):
    gray = np.array(img_crop.convert("L"))
    if gray.size == 0:
        return False
    dark_fraction = float((gray < 140).sum()) / gray.size
    return dark_fraction > threshold


def has_handwriting(img_crop, threshold=0.02):
    """Cheap pre-check for whether a write-in field has anything written in it,
    before spending an OCR call on it. Only looks at the upper ~65% of the box
    so the pre-printed underline itself (which sits at the very bottom) isn't
    mistaken for handwritten content."""
    w, h = img_crop.size
    if w == 0 or h == 0:
        return False
    upper = img_crop.crop((0, 0, w, int(h * 0.65)))
    gray = np.array(upper.convert("L"))
    if gray.size == 0:
        return False
    dark_fraction = float((gray < 140).sum()) / gray.size
    return dark_fraction > threshold


def _upscale(img_crop, factor=3):
    w, h = img_crop.size
    if w == 0 or h == 0:
        return img_crop
    return img_crop.resize((w * factor, h * factor), Image.LANCZOS)


def ocr_price(img_crop):
    """Returns (raw_text, parsed_price_or_None)."""
    up = _upscale(img_crop)
    raw = pytesseract.image_to_string(
        up, config="--psm 7 -c tessedit_char_whitelist=0123456789,."
    ).strip()
    digits = re.sub(r"[^0-9.]", "", raw.replace(",", ""))
    try:
        price = float(digits) if digits else None
    except ValueError:
        price = None
    return raw, price


def ocr_text(img_crop):
    up = _upscale(img_crop)
    return pytesseract.image_to_string(up, config="--psm 7").strip()


def pdf_to_page_images(pdf_path, dpi=DPI):
    return convert_from_path(pdf_path, dpi=dpi)


def build_item_lookup(schema, country):
    """item_id -> {label, unit, food_group_label}"""
    lookup = {}
    group_labels = {g["id"]: g["label"] for g in schema["food_groups"]}
    item_lists = schema["countries"][country]["item_lists"]
    for group_id, items in item_lists.items():
        for item in items:
            lookup[(group_id, item["item_id"])] = {
                "item_label": item["label"],
                "unit": item["default_unit"],
                "food_group_label": group_labels.get(group_id, group_id),
            }
    return lookup


def extract_from_images(page_images, fieldmap, schema, source_channel="paper_scan"):
    country = fieldmap["country"]
    item_lookup = build_item_lookup(schema, country)

    submission = {"country": country, "currency": schema["countries"][country]["currency"],
                  "source_channel": source_channel}
    for f in fieldmap["header_fields"]:
        page_img = page_images[f["page"] - 1]
        field_crop = crop(page_img, pt_bbox_to_px(f["bbox"]))
        submission[f["field_id"]] = ocr_text(field_crop) if has_handwriting(field_crop) else ""

    line_items = []
    for f in fieldmap["item_fields"]:
        page_img = page_images[f["page"] - 1]
        checkbox_px = pt_bbox_to_px(f["checkbox_bbox"])
        if not is_checkbox_filled(crop(page_img, checkbox_px)):
            continue
        price_px = pt_bbox_to_px(f["price_bbox"])
        raw_price, price = ocr_price(crop(page_img, price_px))
        meta = item_lookup.get((f["food_group_id"], f["item_id"]), {})
        line_items.append({
            "food_group_id": f["food_group_id"],
            "food_group_label": meta.get("food_group_label"),
            "item_id": f["item_id"],
            "item_label": meta.get("item_label"),
            "unit": meta.get("unit"),
            "price": price,
            "raw_price_text": raw_price,
            "is_write_in": False,
            "needs_review": price is None,
        })

    for f in fieldmap["write_in_fields"]:
        page_img = page_images[f["page"] - 1]
        name_px = pt_bbox_to_px(f["item_name_bbox"])
        name_crop = crop(page_img, name_px)
        if not has_handwriting(name_crop):
            continue  # blank write-in row -- skip without wasting an OCR call
        item_text = ocr_text(name_crop)
        if len(re.sub(r"[^A-Za-z]", "", item_text)) < 2:
            continue  # OCR noise (e.g. picked up stray marks), not real text
        unit_px = pt_bbox_to_px(f["unit_bbox"])
        unit_text = ocr_text(crop(page_img, unit_px))
        price_px = pt_bbox_to_px(f["price_bbox"])
        raw_price, price = ocr_price(crop(page_img, price_px))
        line_items.append({
            "food_group_id": f["food_group_id"],
            "food_group_label": None,
            "item_id": None,
            "item_label": item_text,
            "unit": unit_text,
            "price": price,
            "raw_price_text": raw_price,
            "is_write_in": True,
            "needs_review": True,  # write-in item names always go to human review
        })

    return submission, line_items


def extract_from_pdf(pdf_path, fieldmap, schema):
    page_images = pdf_to_page_images(pdf_path)
    return extract_from_images(page_images, fieldmap, schema)


def process_one(pdf_path, fieldmap, schema, form_id):
    submission, line_items = extract_from_pdf(pdf_path, fieldmap, schema)
    submission["form_id"] = form_id
    for li in line_items:
        li["form_id"] = form_id
    return submission, line_items


def main():
    args = sys.argv[1:]
    if args and args[0] == "--batch":
        folder, fieldmap_path, schema_path, out_base = args[1], args[2], args[3], args[4]
        pdf_paths = sorted(glob.glob(f"{folder}/*.pdf"))
    else:
        pdf_paths = [args[0]]
        fieldmap_path, schema_path, out_base = args[1], args[2], args[3]

    with open(fieldmap_path) as f:
        fieldmap = json.load(f)
    with open(schema_path) as f:
        schema = json.load(f)

    all_submissions, all_line_items = [], []
    for i, pdf_path in enumerate(pdf_paths, start=1):
        form_id = pdf_path.split("/")[-1].rsplit(".", 1)[0]
        print(f"[{i}/{len(pdf_paths)}] extracting {pdf_path} ...")
        submission, line_items = process_one(pdf_path, fieldmap, schema, form_id)
        all_submissions.append(submission)
        all_line_items.extend(line_items)

    pd.DataFrame(all_submissions).to_csv(f"{out_base}_submissions.csv", index=False)
    pd.DataFrame(all_line_items).to_csv(f"{out_base}_line_items.csv", index=False)
    n_review = sum(1 for li in all_line_items if li["needs_review"])
    print(f"Wrote {out_base}_submissions.csv ({len(all_submissions)} forms) and "
          f"{out_base}_line_items.csv ({len(all_line_items)} rows, {n_review} flagged for review)")


if __name__ == "__main__":
    main()
